<?php
/**
 * SupplierAddressApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\SAP\PurchaseOrder\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BeLenka\SAP\PurchaseOrder\ApiException;
use BeLenka\SAP\PurchaseOrder\Configuration;
use BeLenka\SAP\PurchaseOrder\HeaderSelector;
use BeLenka\SAP\PurchaseOrder\ObjectSerializer;

/**
 * SupplierAddressApi Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SupplierAddressApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'purchaseOrderPurchaseOrderSupplierAddressGet' => [
            'application/json',
        ],
        'purchaseOrderSupplierAddressGet' => [
            'application/json',
        ],
        'purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet' => [
            'application/json',
        ],
        'purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch' => [
            'application/json',
        ],
        'purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation purchaseOrderPurchaseOrderSupplierAddressGet
     *
     * Get related _SupplierAddress
     *
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType|\BeLenka\SAP\PurchaseOrder\Model\Error
     */
    public function purchaseOrderPurchaseOrderSupplierAddressGet($purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'][0])
    {
        list($response) = $this->purchaseOrderPurchaseOrderSupplierAddressGetWithHttpInfo($purchase_order, $select, $expand, $contentType);
        return $response;
    }

    /**
     * Operation purchaseOrderPurchaseOrderSupplierAddressGetWithHttpInfo
     *
     * Get related _SupplierAddress
     *
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType|\BeLenka\SAP\PurchaseOrder\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function purchaseOrderPurchaseOrderSupplierAddressGetWithHttpInfo($purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'][0])
    {
        $request = $this->purchaseOrderPurchaseOrderSupplierAddressGetRequest($purchase_order, $select, $expand, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation purchaseOrderPurchaseOrderSupplierAddressGetAsync
     *
     * Get related _SupplierAddress
     *
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderPurchaseOrderSupplierAddressGetAsync($purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'][0])
    {
        return $this->purchaseOrderPurchaseOrderSupplierAddressGetAsyncWithHttpInfo($purchase_order, $select, $expand, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation purchaseOrderPurchaseOrderSupplierAddressGetAsyncWithHttpInfo
     *
     * Get related _SupplierAddress
     *
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderPurchaseOrderSupplierAddressGetAsyncWithHttpInfo($purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'][0])
    {
        $returnType = '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType';
        $request = $this->purchaseOrderPurchaseOrderSupplierAddressGetRequest($purchase_order, $select, $expand, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'purchaseOrderPurchaseOrderSupplierAddressGet'
     *
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function purchaseOrderPurchaseOrderSupplierAddressGetRequest($purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderPurchaseOrderSupplierAddressGet'][0])
    {

        // verify the required parameter 'purchase_order' is set
        if ($purchase_order === null || (is_array($purchase_order) && count($purchase_order) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $purchase_order when calling purchaseOrderPurchaseOrderSupplierAddressGet'
            );
        }
        if (strlen($purchase_order) > 10) {
            throw new \InvalidArgumentException('invalid length for "$purchase_order" when calling SupplierAddressApi.purchaseOrderPurchaseOrderSupplierAddressGet, must be smaller than or equal to 10.');
        }
        
        
        

        $resourcePath = '/PurchaseOrder/{PurchaseOrder}/_SupplierAddress';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expand,
            '$expand', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($purchase_order !== null) {
            $resourcePath = str_replace(
                '{' . 'PurchaseOrder' . '}',
                ObjectSerializer::toPathValue($purchase_order),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation purchaseOrderSupplierAddressGet
     *
     * Get entities from PurchaseOrderSupplierAddress
     *
     * @param  int $top Show only the first n items, see [Paging - Top](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter) (optional)
     * @param  bool $count Include count of items, see [Count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType|\BeLenka\SAP\PurchaseOrder\Model\Error
     */
    public function purchaseOrderSupplierAddressGet($top = null, $skip = null, $filter = null, $count = null, $orderby = null, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressGet'][0])
    {
        list($response) = $this->purchaseOrderSupplierAddressGetWithHttpInfo($top, $skip, $filter, $count, $orderby, $select, $expand, $contentType);
        return $response;
    }

    /**
     * Operation purchaseOrderSupplierAddressGetWithHttpInfo
     *
     * Get entities from PurchaseOrderSupplierAddress
     *
     * @param  int $top Show only the first n items, see [Paging - Top](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter) (optional)
     * @param  bool $count Include count of items, see [Count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType|\BeLenka\SAP\PurchaseOrder\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function purchaseOrderSupplierAddressGetWithHttpInfo($top = null, $skip = null, $filter = null, $count = null, $orderby = null, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressGet'][0])
    {
        $request = $this->purchaseOrderSupplierAddressGetRequest($top, $skip, $filter, $count, $orderby, $select, $expand, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation purchaseOrderSupplierAddressGetAsync
     *
     * Get entities from PurchaseOrderSupplierAddress
     *
     * @param  int $top Show only the first n items, see [Paging - Top](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter) (optional)
     * @param  bool $count Include count of items, see [Count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressGetAsync($top = null, $skip = null, $filter = null, $count = null, $orderby = null, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressGet'][0])
    {
        return $this->purchaseOrderSupplierAddressGetAsyncWithHttpInfo($top, $skip, $filter, $count, $orderby, $select, $expand, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation purchaseOrderSupplierAddressGetAsyncWithHttpInfo
     *
     * Get entities from PurchaseOrderSupplierAddress
     *
     * @param  int $top Show only the first n items, see [Paging - Top](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter) (optional)
     * @param  bool $count Include count of items, see [Count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressGetAsyncWithHttpInfo($top = null, $skip = null, $filter = null, $count = null, $orderby = null, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressGet'][0])
    {
        $returnType = '\BeLenka\SAP\PurchaseOrder\Model\CollectionOfPurchaseOrderSupplierAddressType';
        $request = $this->purchaseOrderSupplierAddressGetRequest($top, $skip, $filter, $count, $orderby, $select, $expand, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'purchaseOrderSupplierAddressGet'
     *
     * @param  int $top Show only the first n items, see [Paging - Top](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop) (optional)
     * @param  int $skip Skip the first n items, see [Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip) (optional)
     * @param  string $filter Filter items by property values, see [Filtering](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter) (optional)
     * @param  bool $count Include count of items, see [Count](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount) (optional)
     * @param  string[] $orderby Order items by property values, see [Sorting](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby) (optional)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function purchaseOrderSupplierAddressGetRequest($top = null, $skip = null, $filter = null, $count = null, $orderby = null, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressGet'][0])
    {

        if ($top !== null && $top < 0) {
            throw new \InvalidArgumentException('invalid value for "$top" when calling SupplierAddressApi.purchaseOrderSupplierAddressGet, must be bigger than or equal to 0.');
        }
        
        if ($skip !== null && $skip < 0) {
            throw new \InvalidArgumentException('invalid value for "$skip" when calling SupplierAddressApi.purchaseOrderSupplierAddressGet, must be bigger than or equal to 0.');
        }
        


        
        
        

        $resourcePath = '/PurchaseOrderSupplierAddress';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $top,
            '$top', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            '$skip', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            '$filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $count,
            '$count', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderby,
            '$orderby', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expand,
            '$expand', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet
     *
     * Get entity from PurchaseOrderSupplierAddress by key
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType|\BeLenka\SAP\PurchaseOrder\Model\Error
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'][0])
    {
        list($response) = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetWithHttpInfo($supplier_address_id, $purchase_order, $select, $expand, $contentType);
        return $response;
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetWithHttpInfo
     *
     * Get entity from PurchaseOrderSupplierAddress by key
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType|\BeLenka\SAP\PurchaseOrder\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetWithHttpInfo($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'][0])
    {
        $request = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetRequest($supplier_address_id, $purchase_order, $select, $expand, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetAsync
     *
     * Get entity from PurchaseOrderSupplierAddress by key
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetAsync($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'][0])
    {
        return $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetAsyncWithHttpInfo($supplier_address_id, $purchase_order, $select, $expand, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetAsyncWithHttpInfo
     *
     * Get entity from PurchaseOrderSupplierAddress by key
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetAsyncWithHttpInfo($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'][0])
    {
        $returnType = '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressType';
        $request = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetRequest($supplier_address_id, $purchase_order, $select, $expand, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGetRequest($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'][0])
    {

        // verify the required parameter 'supplier_address_id' is set
        if ($supplier_address_id === null || (is_array($supplier_address_id) && count($supplier_address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $supplier_address_id when calling purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'
            );
        }
        if (strlen($supplier_address_id) > 10) {
            throw new \InvalidArgumentException('invalid length for "$supplier_address_id" when calling SupplierAddressApi.purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'purchase_order' is set
        if ($purchase_order === null || (is_array($purchase_order) && count($purchase_order) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $purchase_order when calling purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet'
            );
        }
        if (strlen($purchase_order) > 10) {
            throw new \InvalidArgumentException('invalid length for "$purchase_order" when calling SupplierAddressApi.purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderGet, must be smaller than or equal to 10.');
        }
        
        
        

        $resourcePath = '/PurchaseOrderSupplierAddress/{SupplierAddressID}/{PurchaseOrder}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expand,
            '$expand', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($supplier_address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'SupplierAddressID' . '}',
                ObjectSerializer::toPathValue($supplier_address_id),
                $resourcePath
            );
        }
        // path params
        if ($purchase_order !== null) {
            $resourcePath = str_replace(
                '{' . 'PurchaseOrder' . '}',
                ObjectSerializer::toPathValue($purchase_order),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch
     *
     * Update entity in PurchaseOrderSupplierAddress
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressTypeUpdate $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'][0])
    {
        $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchWithHttpInfo($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, $contentType);
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchWithHttpInfo
     *
     * Update entity in PurchaseOrderSupplierAddress
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressTypeUpdate $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchWithHttpInfo($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'][0])
    {
        $request = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchRequest($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                
            }
            throw $e;
        }
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchAsync
     *
     * Update entity in PurchaseOrderSupplierAddress
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressTypeUpdate $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchAsync($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'][0])
    {
        return $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchAsyncWithHttpInfo($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchAsyncWithHttpInfo
     *
     * Update entity in PurchaseOrderSupplierAddress
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressTypeUpdate $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchAsyncWithHttpInfo($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'][0])
    {
        $returnType = '';
        $request = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchRequest($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderSupplierAddressTypeUpdate $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update New property values (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatchRequest($supplier_address_id, $purchase_order, $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'][0])
    {

        // verify the required parameter 'supplier_address_id' is set
        if ($supplier_address_id === null || (is_array($supplier_address_id) && count($supplier_address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $supplier_address_id when calling purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'
            );
        }
        if (strlen($supplier_address_id) > 10) {
            throw new \InvalidArgumentException('invalid length for "$supplier_address_id" when calling SupplierAddressApi.purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'purchase_order' is set
        if ($purchase_order === null || (is_array($purchase_order) && count($purchase_order) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $purchase_order when calling purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'
            );
        }
        if (strlen($purchase_order) > 10) {
            throw new \InvalidArgumentException('invalid length for "$purchase_order" when calling SupplierAddressApi.purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update' is set
        if ($com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update === null || (is_array($com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update) && count($com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update when calling purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPatch'
            );
        }


        $resourcePath = '/PurchaseOrderSupplierAddress/{SupplierAddressID}/{PurchaseOrder}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($supplier_address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'SupplierAddressID' . '}',
                ObjectSerializer::toPathValue($supplier_address_id),
                $resourcePath
            );
        }
        // path params
        if ($purchase_order !== null) {
            $resourcePath = str_replace(
                '{' . 'PurchaseOrder' . '}',
                ObjectSerializer::toPathValue($purchase_order),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update));
            } else {
                $httpBody = $com_sap_gateway_srvd_a2x_api_purchaseorder2_v0001_purchase_order_supplier_address_type_update;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet
     *
     * Get related _PurchaseOrderTP
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType|\BeLenka\SAP\PurchaseOrder\Model\Error
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'][0])
    {
        list($response) = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetWithHttpInfo($supplier_address_id, $purchase_order, $select, $expand, $contentType);
        return $response;
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetWithHttpInfo
     *
     * Get related _PurchaseOrderTP
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'] to see the possible values for this operation
     *
     * @throws \BeLenka\SAP\PurchaseOrder\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType|\BeLenka\SAP\PurchaseOrder\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetWithHttpInfo($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'][0])
    {
        $request = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetRequest($supplier_address_id, $purchase_order, $select, $expand, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                
            }

            $returnType = '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                
            }
            throw $e;
        }
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetAsync
     *
     * Get related _PurchaseOrderTP
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetAsync($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'][0])
    {
        return $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetAsyncWithHttpInfo($supplier_address_id, $purchase_order, $select, $expand, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetAsyncWithHttpInfo
     *
     * Get related _PurchaseOrderTP
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetAsyncWithHttpInfo($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'][0])
    {
        $returnType = '\BeLenka\SAP\PurchaseOrder\Model\ComSapGatewaySrvdA2xApiPurchaseorder2V0001PurchaseOrderType';
        $request = $this->purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetRequest($supplier_address_id, $purchase_order, $select, $expand, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'
     *
     * @param  string $supplier_address_id Address Number (required)
     * @param  string $purchase_order Purchase Order Number (required)
     * @param  string[] $select Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)
     * @param  string[] $expand Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGetRequest($supplier_address_id, $purchase_order, $select = null, $expand = null, string $contentType = self::contentTypes['purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'][0])
    {

        // verify the required parameter 'supplier_address_id' is set
        if ($supplier_address_id === null || (is_array($supplier_address_id) && count($supplier_address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $supplier_address_id when calling purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'
            );
        }
        if (strlen($supplier_address_id) > 10) {
            throw new \InvalidArgumentException('invalid length for "$supplier_address_id" when calling SupplierAddressApi.purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet, must be smaller than or equal to 10.');
        }
        
        // verify the required parameter 'purchase_order' is set
        if ($purchase_order === null || (is_array($purchase_order) && count($purchase_order) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $purchase_order when calling purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet'
            );
        }
        if (strlen($purchase_order) > 10) {
            throw new \InvalidArgumentException('invalid length for "$purchase_order" when calling SupplierAddressApi.purchaseOrderSupplierAddressSupplierAddressIDPurchaseOrderPurchaseOrderTPGet, must be smaller than or equal to 10.');
        }
        
        
        

        $resourcePath = '/PurchaseOrderSupplierAddress/{SupplierAddressID}/{PurchaseOrder}/_PurchaseOrderTP';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $select,
            '$select', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expand,
            '$expand', // param base name
            'array', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($supplier_address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'SupplierAddressID' . '}',
                ObjectSerializer::toPathValue($supplier_address_id),
                $resourcePath
            );
        }
        // path params
        if ($purchase_order !== null) {
            $resourcePath = str_replace(
                '{' . 'PurchaseOrder' . '}',
                ObjectSerializer::toPathValue($purchase_order),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
