<?php
/**
 * AccountAssignmentApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\PurchaseOrder\Test\Api;

use \BeLenka\SAP\PurchaseOrder\Configuration;
use \BeLenka\SAP\PurchaseOrder\ApiException;
use \BeLenka\SAP\PurchaseOrder\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AccountAssignmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountAssignmentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for purchaseOrderAccountAssignmentGet
     *
     * Get entities from PurchaseOrderAccountAssignment.
     *
     */
    public function testPurchaseOrderAccountAssignmentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberGet
     *
     * Get entity from PurchaseOrderAccountAssignment by key.
     *
     */
    public function testPurchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberPatch
     *
     * Update entity in PurchaseOrderAccountAssignment.
     *
     */
    public function testPurchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberPurchaseOrderGet
     *
     * Get related _PurchaseOrder.
     *
     */
    public function testPurchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberPurchaseOrderGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberPurchaseOrderItemGet
     *
     * Get related _PurchaseOrderItem.
     *
     */
    public function testPurchaseOrderAccountAssignmentPurchaseOrderPurchaseOrderItemAccountAssignmentNumberPurchaseOrderItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderItemPurchaseOrderPurchaseOrderItemPurOrdAccountAssignmentGet
     *
     * Get entities from related _PurOrdAccountAssignment.
     *
     */
    public function testPurchaseOrderItemPurchaseOrderPurchaseOrderItemPurOrdAccountAssignmentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderItemPurchaseOrderPurchaseOrderItemPurOrdAccountAssignmentPost
     *
     * Add new entity to related _PurOrdAccountAssignment.
     *
     */
    public function testPurchaseOrderItemPurchaseOrderPurchaseOrderItemPurOrdAccountAssignmentPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
