<?php
/**
 * InvoicingPlanApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\PurchaseOrder\Test\Api;

use \BeLenka\SAP\PurchaseOrder\Configuration;
use \BeLenka\SAP\PurchaseOrder\ApiException;
use \BeLenka\SAP\PurchaseOrder\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InvoicingPlanApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicingPlanApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for purchaseOrderInvoicingPlanGet
     *
     * Get entities from PurchaseOrderInvoicingPlan.
     *
     */
    public function testPurchaseOrderInvoicingPlanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderInvoicingPlanItemPurchaseOrderPurchaseOrderItemInvoicingPlanItemInvoicingPlanPurchaseOrderInvoicingPlanGet
     *
     * Get related _PurchaseOrderInvoicingPlan.
     *
     */
    public function testPurchaseOrderInvoicingPlanItemPurchaseOrderPurchaseOrderItemInvoicingPlanItemInvoicingPlanPurchaseOrderInvoicingPlanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanGet
     *
     * Get entity from PurchaseOrderInvoicingPlan by key.
     *
     */
    public function testPurchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPOInvoicingPlanItemGet
     *
     * Get entities from related _POInvoicingPlanItem.
     *
     */
    public function testPurchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPOInvoicingPlanItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPOInvoicingPlanItemPost
     *
     * Add new entity to related _POInvoicingPlanItem.
     *
     */
    public function testPurchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPOInvoicingPlanItemPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPatch
     *
     * Update entity in PurchaseOrderInvoicingPlan.
     *
     */
    public function testPurchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPurchaseOrderGet
     *
     * Get related _PurchaseOrder.
     *
     */
    public function testPurchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPurchaseOrderGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPurchaseOrderItemGet
     *
     * Get related _PurchaseOrderItem.
     *
     */
    public function testPurchaseOrderInvoicingPlanPurchaseOrderPurchaseOrderItemInvoicingPlanPurchaseOrderItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderItemPurchaseOrderPurchaseOrderItemPurchaseOrderInvoicingPlanGet
     *
     * Get entities from related _PurchaseOrderInvoicingPlan.
     *
     */
    public function testPurchaseOrderItemPurchaseOrderPurchaseOrderItemPurchaseOrderInvoicingPlanGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderItemPurchaseOrderPurchaseOrderItemPurchaseOrderInvoicingPlanPost
     *
     * Add new entity to related _PurchaseOrderInvoicingPlan.
     *
     */
    public function testPurchaseOrderItemPurchaseOrderPurchaseOrderItemPurchaseOrderInvoicingPlanPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
