<?php
/**
 * SubcontractingComponentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\PurchaseOrder\Test\Api;

use \BeLenka\SAP\PurchaseOrder\Configuration;
use \BeLenka\SAP\PurchaseOrder\ApiException;
use \BeLenka\SAP\PurchaseOrder\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SubcontractingComponentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\PurchaseOrder
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubcontractingComponentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for pOSubcontractingComponentGet
     *
     * Get entities from POSubcontractingComponent.
     *
     */
    public function testPOSubcontractingComponentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypeGet
     *
     * Get entity from POSubcontractingComponent by key.
     *
     */
    public function testPOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypePatch
     *
     * Update entity in POSubcontractingComponent.
     *
     */
    public function testPOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypePurchaseOrderGet
     *
     * Get related _PurchaseOrder.
     *
     */
    public function testPOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypePurchaseOrderGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypePurchaseOrderItemGet
     *
     * Get related _PurchaseOrderItem.
     *
     */
    public function testPOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypePurchaseOrderItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypeScheduleLineGet
     *
     * Get related _ScheduleLine.
     *
     */
    public function testPOSubcontractingComponentPurchaseOrderPurchaseOrderItemScheduleLineReservationItemRecordTypeScheduleLineGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderScheduleLinePurchaseOrderPurchaseOrderItemScheduleLineSubcontractingComponentGet
     *
     * Get entities from related _SubcontractingComponent.
     *
     */
    public function testPurchaseOrderScheduleLinePurchaseOrderPurchaseOrderItemScheduleLineSubcontractingComponentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseOrderScheduleLinePurchaseOrderPurchaseOrderItemScheduleLineSubcontractingComponentPost
     *
     * Add new entity to related _SubcontractingComponent.
     *
     */
    public function testPurchaseOrderScheduleLinePurchaseOrderPurchaseOrderItemScheduleLineSubcontractingComponentPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
